### ISSUE TITLE
Allow labels with Garmin data

### ISSUE THREAD

**Issue by tbidne** [tbidne/pacer#2]
Currently, labels are specified per run in `runs.toml`:

```toml
[[runs]]
datetime = 2024-10-25T12:00:00-08:00
distance = 'marathon'
duration = '3h20m'
labels = ['official', 'marathon']
title= 'Some Marathon'
```

This allows us to later filter by them in a chart request:

```toml
[[charts]]
title = 'Marathons'
filters = ['label marathon', 'datetime >= 2024']
y-axis = 'duration'
```

As far as I can tell, garmin does not provide any way to attach arbitrary "labels" (text) to a run. Or if it does, it does not seem to show up in the exported CSV. This means we cannot use labels with garmin runs.

However, there is a potential workaround. Instead of attaching labels to the run, have a separate `run_labels.toml` with something like:

```toml
[[run_labels]]
datetime = 2024-10-25T12:00:00-08:00
labels = ['official', 'marathon']
```

Then we'd parse `run_labels.toml` into a map, and when deserializing our `Run` type, we'd lookup the run in the map to get the labels. This works because `datetime`s are required to be unique.

To keep usage with `runs.toml` simple, we probably want to continue to allow `labels` to exist directly in the toml. This would mean it is possible we have labels specified in two places for a particular run: `runs.toml` _and_ `run_labels.toml`. Probably the best solution here is to take the union.
